# Site settings
title: zhaopin Blog
SEOTitle: 智联的博客 | zhaopin Blog
header-img: img/home-bg-o.jpg
email: zhao.liu@zhaopin.com.cn
description: "关于程序与设计、黑客与画家 | 智联，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @智联招聘 的博客，与你一起发现更大的世界。"
keyword: "智联招聘, zhilianzhaopin, zhaopin, 智联的博客, 智联Blog, 博客, io网站, 互联网, Web, JavaScript, 前端, 设计, iOS, Android"
url: "zpmobile.tech"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     zhilianzhaopin
zhihu_username:     shuang-shou-lian-xu-pu-tong-quan-39
github_username:    zhilianzhaopin
twitter_username:   zhilianzhaopin
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this
